# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, max_length=10, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.School')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
