# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20161121_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
